# Generated by Django 3.2.16 on 2022-12-14 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('valorDivida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Divida')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=230, verbose_name='Rua')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('combustivelNoTanque', models.IntegerField(verbose_name='Combustivel no Tanque')),
                ('quilometragem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quilometragem')),
                ('alugado', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Alugado')),
                ('precodiaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da Diaria')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Veiculo',
                'verbose_name_plural': 'Veiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locacao.veiculo')),
                ('potencia', models.IntegerField(verbose_name='Potencia do Motor')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['placa'],
            },
            bases=('locacao.veiculo',),
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('veiculo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locacao.veiculo')),
                ('cilindrada', models.IntegerField(verbose_name='Cilindradas')),
            ],
            options={
                'verbose_name': 'Moto',
                'verbose_name_plural': 'Motos',
                'ordering': ['placa'],
            },
            bases=('locacao.veiculo',),
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicial', models.DateField(default=django.utils.timezone.now, verbose_name='Data Aluguel')),
                ('data_dev', models.DateField(verbose_name='Data develução')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacao.cliente')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacao.veiculo')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
                'ordering': ['data_inicial'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locacao.endereco'),
        ),
    ]
